import Head from "next/head";
import Image from "next/image";
import { Poppins } from "next/font/google";
import Slider from "../../components/Slider";
import WhyUs from "../../components/WhyUs";
import OfferTab from "../../components/OfferTab";
import Carousel from "../../components/Carousel";
import DrBooking from "../../components/DrBooking";
import TestMedicine from "../../components/TestMedicine";
import CustomerSupport from "../../components/CustomerSupport";
import FaceBook from "../../components/FaceBook";
import Faq from "../../components/Faq";
import Script from "next/script";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-poppins",
});

export default function Home() {

  return (
    <>
      <Head>
        <title>Mr Healer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png" />
        <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png" />
        <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png" />
        <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png" />
        <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png" />
        <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png" />
        <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png" />
        <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="msapplication-TileImage" content="/ms-icon-144x144.png" />
        <meta name="theme-color" content="#ffffff"></meta>
        <link rel="icon" href="/favicon.ico" />
        {/* <script src="/js/main.js"></script> */}
        {/* <script>
{`      const navLinks = document.querySelectorAll("#nav a");

        for (const link of navLinks) {
        link.addEventListener("click", clickHandler);
        }

        function clickHandler(e) {
        e.preventDefault();
        const href = this.getAttribute("href");
        const offsetTop = document.querySelector(href).offsetTop;

        scroll({
            top: offsetTop,
            behavior: "smooth"
        });
        }`}
    </script> */}
      {/* <script
    async
    src="https://www.youtube.com/iframe_api"
   /> */}
      </Head>
      <main className={poppins.className}>
        <Slider />
        <WhyUs />
        <OfferTab  />
        <Carousel />
        <DrBooking />
        <TestMedicine />
        <CustomerSupport />
        <FaceBook />
        <Faq />
      </main>

      <script src={"/js/main.js"} async ></script>
    </>
  );
}
